# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import file_pb2 as file__pb2


class FileServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.download = channel.stream_stream(
        '/bidirectional.FileServer/download',
        request_serializer=file__pb2.Request.SerializeToString,
        response_deserializer=file__pb2.Response.FromString,
        )


class FileServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def download(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'download': grpc.stream_stream_rpc_method_handler(
          servicer.download,
          request_deserializer=file__pb2.Request.FromString,
          response_serializer=file__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bidirectional.FileServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
